//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationPaises.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pais
    {
        public int Id { get; set; }
        public string codId { get; set; }
        public string name { get; set; }
        public string local { get; set; }
        public string currency_id { get; set; }
    }
}
